### PR TITLE
Reference workspaces by number

### PR DESCRIPTION
**Pull request by leosunmo**
Pretty straight forward. Added a `number` option to everything that references a workspace. This makes it nicer when you update your theme or make any changes to the `i3-wm` Xresources files as it stop i3 from creating new workspaces with the same index but different name/colour.

This does mean that you will have to re-create the workspace in order to see the style change. A workaround would be to "rename" the workspace using the built-in function to do so in i3.
https://i3wm.org/docs/userguide.html#_changing_named_workspaces_moving_to_workspaces has more details.

We could potentially create a script and bind it to `$mod+Shift+r` so that we
1. Refresh the xresources database with `xrdb`
2. Renames all the workspaces to give them their new colour/names
3. Actually execute `i3-msg restart` to refresh i3 specific config.

### CODE REVIEW

**Comment by leosunmo** [comment]
Discovered a bug already. When I restarted the first workspace didn't have a coloured block until I recreated it.

**Comment by kgilmer** [comment]
Ok I'll hold for bug.

**Comment by leosunmo** [comment]
Still seeing some strange behaviour here. I have an application bound to workspace 6. When I open the application on a different workspace it opens it on 6 and I can see it in the bar. 
When I use $mod+6 to get to that workspace it opens a new workspace 6 (whut). Once I get to the workspace 6 (using mouse or $mod+tab) with my app in it, it's fine, it always opens the "correct" workspace 6.

**Comment by leosunmo** [comment]
hm okay, this is annoying. If I want to make sure we can change themes on the go I add `number` to the bindsyms. This enabled us to change theme, and the new workspace colours will only apply when you _recreate_ the workspace. This is desired behaviour in my opinion since it allows you to easily test new themes without disrupting existing workspaces.

The problem with adding `number` to the bindsyms is this issue: https://faq.i3wm.org/question/3798/workspace-1-not-getting-name-set-in-config-at-startup/index.html

At startup we get some default `1` workspace instead of `$ws1`. Very annoying.

If we leave the `number` everywhere expect bindsym, like the linked i3 FAQ suggests, it breaks all workspaces upon loading a new Xresources theme, because the bindsyms are now referencing a new set of `$ws*` variables by name, not number.

**Comment by leosunmo** [comment]
As described here: https://github.com/i3/i3/issues/1414#issuecomment-72822818
It will not use the bindsyms if they contain `number`, which seems to still hold true. If I use the following config, upon rebooting I get WS 11 and WS 12 on my two screens respectively.

```
...
bindsym $mod+0 workspace number $ws10
bindsym $mod+Ctrl+1 workspace $ws11
bindsym $mod+Ctrl+2 workspace $ws12
bindsym $mod+Ctrl+3 workspace $ws13
...
```

**Comment by leosunmo** [comment]
I think the best way forward is to _not_ use `number` in the bindsyms, but use them everywhere else, and create a script that refreshes all the workspace names upon pressing `$mod-Shift-R`.

**Comment by leosunmo** [comment]
So this is weird. In the latest version of i3 they are using `number` by default now. I wonder if this behaviour has changed? https://github.com/i3/i3/commit/e6662df114329ba45bd1d117c731b3dc8bdd13fb

**Comment by leosunmo** [comment]
This seems to have been fixed in i3 now. https://github.com/i3/i3/issues/3527#event-2670342339

**Comment by kgilmer** [comment]
Sweet!  We need to wait for a release to take the change I'm guessing...

**Comment by leosunmo** [comment]
This _should_ be in version 4.17.0 and now 4.17.1. Let's update speed ricer with the new version @kgilmer !

**Comment by kgilmer** [comment]
Speed-ricer now has 4.17.1.  Does it work?

**Comment by leosunmo** [comment]
Initial tests seemed fine but I'll have to actually spend some time. I'll do it as soon as I have some time!

**Comment by leosunmo** [comment]
This is now working as I wanted. What this means is that if I completely change my theme (which will regenerate the `$ws#` variables in i3) I am still able to switch to the "old" workspaces and new "ghost" workspaces aren't created. This should unlock a _way_ smoother live theme changing experience.

**Review by kgilmer — APPROVED** [review]
Awesome!  Works as expected.

image

**Comment by leosunmo** [comment]
:tada:

**Pull request merged**
