### PR TITLE
Remove redundant line

### PR DESCRIPTION
**Pull request by cheginit**

### CODE REVIEW

**Comment by kgilmer** [comment]
Hmm, not sure about the motive on this one.  The font line is kind of a no-op except that i3 complains on startup about the missing entry.  There are some dialogs it surfaces at times (invalid config) in these cases this font is used.  Am I missing something?

**Comment by cheginit** [comment]
It seems that this line is used to set the font for the bar and it's repeated in the bar block couple of lines below. So I figured it doesn't make sense to set the font for the bar outside the bar block.

**Comment by kgilmer** [comment]
It's my understanding that <root>.font and bar.font are two distinct config settings in i3.  If you remove the root statement, and restart i3, I believe you'll see an error message in the log from i3 stating that font is undefined.

https://i3wm.org/docs/userguide.html#fonts

https://i3wm.org/docs/userguide.html#_font

**Comment by cheginit** [comment]
Oh, I see. So that font is for the i3 itself. I thought since it's exactly the same as the bar font thought you forgot to delete it.

I don't have this line in my config and not seeing any errors.

**Pull request closed without merging**
