### PR TITLE
configurable workspace keys

### PR DESCRIPTION
**Pull request by ukaszg**
Allow modification of workspace shortcuts.

### CODE REVIEW

**Comment by moritzheiber** [comment]
@ukaszg I'm assuming you've verified this works? :wink: 
@kgilmer What do you think? I don't see a reason as to why this shouldn't be merged

**Comment by moritzheiber** [comment]
@ukaszg Also, we'd appreciate a PR for [the Xresources reference on the website](https://github.com/regolith-linux/website/blob/master/content/en/docs/Reference/xresources.md) once this gets merged :heart:

**Comment by ukaszg** [comment]
yes it works, I'm currently using it renaming all workspaces and setting keys to: grave,1,2...9
added a pull request for the reference file

**Comment by kgilmer** [comment]
Impeccable, thanks @ukaszg !  :smile:

**Pull request merged**
