### PR TITLE
deprecating startnum

### PR DESCRIPTION
**Pull request by ferdinandyb**
The pull request https://github.com/regolith-linux/regolith-i3xrocks-config/pull/82 will deprecate the `--startnum` for `next-workspace`.

### CODE REVIEW

**Comment by ferdinandyb** [comment]
I realized a comment was wrong (Mod1 is Alt not Shift) and that there is a second place where --startnum was used

**Comment by moritzheiber** [comment]
@ferdinandyb I'm afraid you'll have to rebase

**Comment by ferdinandyb** [comment]
oh yeah, some time has passed, I'll fix it later

**Comment by ferdinandyb** [comment]
Note, that https://github.com/regolith-linux/regolith-i3-gaps-config/commit/9d260b0e5333c082aa2bd8adc1430095a6f2da95 also noted that the comment and the actual command was wrong, but actually, the comment was in error, since we use `$mod` for "move and follow" maneuvers with the workspace numbers as well.

And I will go ahead and merge now, since the related update with `next-workspace` is already merged.

**Comment by kgilmer** [comment]
Beautiful, thank you!

**Pull request merged**
