### PR TITLE
Made todo window floating

### PR DESCRIPTION
**Pull request by cheginit**
The PR makes the todo blocklet window floating on click.

### CODE REVIEW

**Comment by kgilmer** [comment]
Hmm, ideally this could be dynamic, such that users without need of td-cli would not have any config items either.  Did you try specifying the class string as a list from a variable?

**Comment by cheginit** [comment]
@kgilmer How about changing the window role to `pop-up` instead of class so not only td-cli but any window with `pop-up` role becomes floating:
```bash
for_window [window_role="pop-up"] floating enable
```

**Comment by kgilmer** [comment]
Can users set the window role for apps they wish the same treatment?

**Comment by cheginit** [comment]
@kgilmer I am not sure if all the `gtk` apps have a `--role` flag. I launch gnome terminal like this:
```bash
/usr/bin/i3-msg -q exec "/usr/bin/gnome-terminal --role=pop-up -e 'td --interactive'"
```

**Comment by kgilmer** [comment]
It seems to be a special feature of `gnome-terminal`.  At least `gnome-control-center` does not support this.  It looks like both title and class are settable for any gtk app though, if that app exposes the gtk options parsing feature.

**Comment by cheginit** [comment]
Yeah, it seems that name and class are the most common flags that are adopted by gtk apps. Which way do you want to go?

**Comment by kgilmer** [comment]
This defines all the properties from which we can predicate floating state: https://i3wm.org/docs/userguide.html#list_of_commands

From my reading, the `instance` property seems to be semantically closest to what we want to express,  however there only seems to be a reliable way of setting `class` on an application, not `instance`.  `role` also seems promising but is inconsistently implemented.  

Between `class` and `name`, `class` seems slightly better to me, if only because it appears more of an internal detail and setting the title seems more user-facing than the class.  I am unaware of any negative repercussions to setting the class at launch time. 

Given all that, what about changing the existing class match of `Gnome-control-center` to, say `popup` or `floating_window`, and then when we launch `td-cli` or `gnome-control-center` we pass the class name accordingly.  So instead of an additional `for_window` expression, we change the existing and the way that `gnome-control-center` is launched.  Problems?

**Comment by kgilmer** [comment]
Another data point: https://superuser.com/questions/1179843/how-to-start-a-firefox-with-a-different-wm-class-or-any-other-altered-property

**Comment by cheginit** [comment]
Yes, I agree, we can certainly do that. I used to do it a while back when I had much more cusotmization in i3 config file. I will make the change.

**Comment by cheginit** [comment]
@kgilmer I just noticed that I used the keybinding that I have in my custom config for `gnome-control-center` which is `mod+g`.

I can revet it back but have a suggestion as well. The `mod+c` key is a very convenient keybinding that can be used for a more frequently used task. For example, I use it for running the rofi calculator. So I change the default keybinding to `mod+g` for `gnome-control-center` and use `mod+c` for [`rofi-calc`](https://github.com/svenstaro/rofi-calc). Some people might prefer to use it for a rofi-based clipboard called [`greenclip`](https://github.com/erebe/greenclip). What do you think?

**Comment by kgilmer** [comment]
It's hard to be objective about keybinding mappings.  I don't see anything wrong with what you're saying but would like to have an objective or quantifiable justification for changing it, to weigh against the user cost of having the keybinding change for them upon upgrade.  

Depending on how you use your computer, the Settings app can be very commonly used.

**Comment by cheginit** [comment]
I see. Perhaps having a full-blown calendar app in terminal like [`calcurse`](https://calcurse.org/) would be a good reason.

**Comment by kgilmer** [comment]
This LGTM @cheginit , is this ready to be merged?

**Comment by cheginit** [comment]
Yes, it's ready.

**Pull request merged**
