### PR TITLE
Use mod+alt+R/L to move between workspaces

### PR DESCRIPTION
**Pull request by ekostem**
Proposal to switch between workspaces using mod+alt and right / left arrows. Makes it easier for continuous movement.

### CODE REVIEW

**Comment by ekostem** [comment]
Accompanying changes:
https://github.com/regolith-linux/remontoire/pull/1
https://github.com/regolith-linux/regolith-conky-config/pull/5

**Comment by kgilmer** [comment]
Hi @ekostem , thanks for your PR.  I do not want to remove the existing keybinding as others that use it would be surprised that it stopped working.  But, I agree that this frequent action could have a more "natural" keybinding as well.  What do you think about `<super>`-`[` and `<super>`-`]`?

**Comment by ekostem** [comment]
Hi @kgilmer , first of all, I really liked Regolith, thanks! Picking these keybindings is mostly personal, however I found `<super> - <alt> -  left/right` complimenting `<super> - arrows` very well. I can move around the windows within a workspace with the latter, and one key more, former extends it to workspaces. Just wanted to share with others :)

**Comment by kgilmer** [comment]
Ah, good point.  I tried it out and I like it :smile: .

**Comment by kgilmer** [comment]
can you update the PR to add the shortcuts instead of replacing the previous keybindings?  I'll merge the PR.

**Comment by kgilmer** [comment]
This was implemented, but not via the PR.

**Pull request closed without merging**
